name: Postman API CI

on:
  push:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run GoRest Collection
        run: newman run GoRest_Collection/Gorest_API.postman_collection.json -e GoRest_Collection/QA_Env.postman_environment.json -r cli,html --reporter-html-export Gorest_Report.html

      - name: Run Swagger PET Collection
        run: newman run Swagger_PET_XMLCollection/Swagger_Pet_API_Xml.postman_collection.json -r cli,html --reporter-html-export Swagger_PET_Report.html

      - name: Run Swagger USER Collection
        run: newman run Swagger_USER_Collection/Swagger_User_API.postman_collection.json -r cli,html --reporter-html-export Swagger_User_Report.html

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Postman-Reports
          path: "*.html"
